/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.2.1, Date: 27-Dec-2018.
 */
#ifndef ADDGRPD_H
#define ADDGRPD_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtbersrc/asn1ber.h"
#include "rtoersrc/asn1oer.h"
#include "rtpersrc/asn1per.h"

#include "DSRC.h"

/**
 * Header file for ASN.1 module AddGrpD
 */
/**************************************************************/
/*                                                            */
/*  CITSLog                                                   */
/*                                                            */
/**************************************************************/
/*
CITSLog ::= SEQUENCE {
   id [0] INTEGER (0..255),
   msgid [1] INTEGER (0..4294967295),
   posid [2] INTEGER (0..255),
   event [3] INTEGER (0..4294967295),
   display [4] INTEGER (0..1),
   hmistate [5] INTEGER (0..1),
   time [6] DDateTime,
   ...
}
*/
#define TV_CITSLog	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN CITSLog {
   OSUINT8 id;
   OSUINT32 msgid;
   OSUINT8 posid;
   OSUINT32 event;
   OSUINT8 display;
   OSUINT8 hmistate;
   DDateTime time_;
   OSRTDList extElem1;
} CITSLog;

EXTERN int asn1E_CITSLog (OSCTXT* pctxt, CITSLog *pvalue, ASN1TagType tagging);

EXTERN int asn1D_CITSLog (OSCTXT* pctxt, CITSLog* pvalue, ASN1TagType tagging, 
   int length);

EXTERN int OEREnc_CITSLog (OSCTXT* pctxt, CITSLog* pvalue);

EXTERN int OERDec_CITSLog (OSCTXT* pctxt, CITSLog* pvalue);

EXTERN int asn1PE_CITSLog (OSCTXT* pctxt, CITSLog* pvalue);

EXTERN int asn1PD_CITSLog (OSCTXT* pctxt, CITSLog* pvalue);

EXTERN void asn1Print_CITSLog (const char* name, const CITSLog* pvalue);

EXTERN int asn1PrtToStr_CITSLog (const char* name, CITSLog* pvalue, char* buffer, 
   OSSIZE bufSize);

EXTERN int asn1PrtToStrm_CITSLog (OSCTXT *pctxt, 
   const char* name, const CITSLog* pvalue);

EXTERN CITSLog* asn1Test_CITSLog (OSCTXT* pctxt);

EXTERN int asn1Init_CITSLog (CITSLog* pvalue);

/**************************************************************/
/*                                                            */
/*  CITSPVD_worklanes                                         */
/*                                                            */
/**************************************************************/
/*
Type was extracted from 'CITSPVD'
*/
typedef struct EXTERN CITSPVD_worklanes {
   OSSIZE n;
   LaneID elem[16];
} CITSPVD_worklanes;

EXTERN int asn1E_CITSPVD_worklanes (OSCTXT* pctxt, CITSPVD_worklanes *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_CITSPVD_worklanes (OSCTXT* pctxt, CITSPVD_worklanes* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_CITSPVD_worklanes (OSCTXT* pctxt, CITSPVD_worklanes* pvalue);

EXTERN int OERDec_CITSPVD_worklanes (OSCTXT* pctxt, CITSPVD_worklanes* pvalue);

EXTERN int asn1PE_CITSPVD_worklanes (OSCTXT* pctxt, CITSPVD_worklanes* pvalue);

EXTERN int asn1PD_CITSPVD_worklanes (OSCTXT* pctxt, CITSPVD_worklanes* pvalue);

EXTERN void asn1Print_CITSPVD_worklanes 
   (const char* name, const CITSPVD_worklanes* pvalue);

EXTERN int asn1PrtToStr_CITSPVD_worklanes (const char* name, 
   CITSPVD_worklanes* pvalue, char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_CITSPVD_worklanes (OSCTXT *pctxt, 
   const char* name, const CITSPVD_worklanes* pvalue);

EXTERN CITSPVD_worklanes* asn1Test_CITSPVD_worklanes (OSCTXT* pctxt);

EXTERN int asn1Init_CITSPVD_worklanes (CITSPVD_worklanes* pvalue);

/**************************************************************/
/*                                                            */
/*  CITSPVD                                                   */
/*                                                            */
/**************************************************************/
/*
CITSPVD ::= SEQUENCE {
   transitStatus [0] TransitStatus OPTIONAL, -- 문�-�림
   acceleration [1] Acceleration OPTIONAL, -- 초당 가속도 Km/h
   worklanes [2] SEQUENCE (SIZE (1..16)) OF LaneID OPTIONAL, -- 도로 작�-� 차로
   curlane [3] LaneID OPTIONAL, -- 차선번호
   vehiclecnt [4] INTEGER (0..255) OPTIONAL, -- 초당 BSM 수신 차량 수
   servicelog [5] CITSLog OPTIONAL, -- 서비스 로그
   ...
}
*/
#define TV_CITSPVD	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN CITSPVD {
   struct {
      unsigned transitStatusPresent : 1;
      unsigned accelerationPresent : 1;
      unsigned worklanesPresent : 1;
      unsigned curlanePresent : 1;
      unsigned vehiclecntPresent : 1;
      unsigned servicelogPresent : 1;
   } m;
   TransitStatus transitStatus;
   Acceleration acceleration;
   CITSPVD_worklanes worklanes;
   LaneID curlane;
   OSUINT8 vehiclecnt;
   CITSLog servicelog;
   OSRTDList extElem1;
} CITSPVD;

EXTERN int asn1E_CITSPVD (OSCTXT* pctxt, CITSPVD *pvalue, ASN1TagType tagging);

EXTERN int asn1D_CITSPVD (OSCTXT* pctxt, CITSPVD* pvalue, ASN1TagType tagging, 
   int length);

EXTERN int OEREnc_CITSPVD (OSCTXT* pctxt, CITSPVD* pvalue);

EXTERN int OERDec_CITSPVD (OSCTXT* pctxt, CITSPVD* pvalue);

EXTERN int asn1PE_CITSPVD (OSCTXT* pctxt, CITSPVD* pvalue);

EXTERN int asn1PD_CITSPVD (OSCTXT* pctxt, CITSPVD* pvalue);

EXTERN void asn1Print_CITSPVD (const char* name, const CITSPVD* pvalue);

EXTERN int asn1PrtToStr_CITSPVD (const char* name, CITSPVD* pvalue, char* buffer, 
   OSSIZE bufSize);

EXTERN int asn1PrtToStrm_CITSPVD (OSCTXT *pctxt, 
   const char* name, const CITSPVD* pvalue);

EXTERN CITSPVD* asn1Test_CITSPVD (OSCTXT* pctxt);

EXTERN int asn1Init_CITSPVD (CITSPVD* pvalue);

/**************************************************************/
/*                                                            */
/*  CITSRSA_laneset                                           */
/*                                                            */
/**************************************************************/
/*
Type was extracted from 'CITSRSA'
*/
typedef struct EXTERN CITSRSA_laneset {
   OSSIZE n;
   LaneID elem[4];
} CITSRSA_laneset;

EXTERN int asn1E_CITSRSA_laneset (OSCTXT* pctxt, CITSRSA_laneset *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_CITSRSA_laneset (OSCTXT* pctxt, CITSRSA_laneset* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_CITSRSA_laneset (OSCTXT* pctxt, CITSRSA_laneset* pvalue);

EXTERN int OERDec_CITSRSA_laneset (OSCTXT* pctxt, CITSRSA_laneset* pvalue);

EXTERN int asn1PE_CITSRSA_laneset (OSCTXT* pctxt, CITSRSA_laneset* pvalue);

EXTERN int asn1PD_CITSRSA_laneset (OSCTXT* pctxt, CITSRSA_laneset* pvalue);

EXTERN void asn1Print_CITSRSA_laneset 
   (const char* name, const CITSRSA_laneset* pvalue);

EXTERN int asn1PrtToStr_CITSRSA_laneset (const char* name, CITSRSA_laneset* pvalue, 
   char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_CITSRSA_laneset (OSCTXT *pctxt, 
   const char* name, const CITSRSA_laneset* pvalue);

EXTERN CITSRSA_laneset* asn1Test_CITSRSA_laneset (OSCTXT* pctxt);

EXTERN int asn1Init_CITSRSA_laneset (CITSRSA_laneset* pvalue);

/**************************************************************/
/*                                                            */
/*  CITSRSA                                                   */
/*                                                            */
/**************************************************************/
/*
CITSRSA ::= SEQUENCE {
   temprature [0] INTEGER (-32767..32767) OPTIONAL, -- 온도
   humidity [1] INTEGER (-32767..32767) OPTIONAL, -- 습도
   percent [2] INTEGER (0..100) OPTIONAL, -- 감속 기준
   limitspeed [3] INTEGER (0..65534) OPTIONAL, -- 제한속도
   lanewidth [4] INTEGER (0..65534) OPTIONAL, -- 도로 폭 cm
   laneset [5] SEQUENCE (SIZE (1..4)) OF LaneID OPTIONAL, -- 차선번호
   ...
}
*/
#define TV_CITSRSA	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN CITSRSA {
   struct {
      unsigned tempraturePresent : 1;
      unsigned humidityPresent : 1;
      unsigned percentPresent : 1;
      unsigned limitspeedPresent : 1;
      unsigned lanewidthPresent : 1;
      unsigned lanesetPresent : 1;
   } m;
   OSINT16 temprature;
   OSINT16 humidity;
   OSUINT8 percent;
   OSUINT16 limitspeed;
   OSUINT16 lanewidth;
   CITSRSA_laneset laneset;
   OSRTDList extElem1;
} CITSRSA;

EXTERN int asn1E_CITSRSA (OSCTXT* pctxt, CITSRSA *pvalue, ASN1TagType tagging);

EXTERN int asn1D_CITSRSA (OSCTXT* pctxt, CITSRSA* pvalue, ASN1TagType tagging, 
   int length);

EXTERN int OEREnc_CITSRSA (OSCTXT* pctxt, CITSRSA* pvalue);

EXTERN int OERDec_CITSRSA (OSCTXT* pctxt, CITSRSA* pvalue);

EXTERN int asn1PE_CITSRSA (OSCTXT* pctxt, CITSRSA* pvalue);

EXTERN int asn1PD_CITSRSA (OSCTXT* pctxt, CITSRSA* pvalue);

EXTERN void asn1Print_CITSRSA (const char* name, const CITSRSA* pvalue);

EXTERN int asn1PrtToStr_CITSRSA (const char* name, CITSRSA* pvalue, char* buffer, 
   OSSIZE bufSize);

EXTERN int asn1PrtToStrm_CITSRSA (OSCTXT *pctxt, 
   const char* name, const CITSRSA* pvalue);

EXTERN CITSRSA* asn1Test_CITSRSA (OSCTXT* pctxt);

EXTERN int asn1Init_CITSRSA (CITSRSA* pvalue);

/**************************************************************/
/*                                                            */
/*  PVD_addGrpD_cits                                          */
/*                                                            */
/**************************************************************/
/*
Type was extracted from 'PVD-addGrpD'
*/
/* List of CITSPVD */
typedef OSRTDList PVD_addGrpD_cits;

EXTERN int asn1E_PVD_addGrpD_cits (OSCTXT* pctxt, PVD_addGrpD_cits *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_PVD_addGrpD_cits (OSCTXT* pctxt, PVD_addGrpD_cits* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_PVD_addGrpD_cits (OSCTXT* pctxt, PVD_addGrpD_cits* pvalue);

EXTERN int OERDec_PVD_addGrpD_cits (OSCTXT* pctxt, PVD_addGrpD_cits* pvalue);

EXTERN int asn1PE_PVD_addGrpD_cits (OSCTXT* pctxt, PVD_addGrpD_cits* pvalue);

EXTERN int asn1PD_PVD_addGrpD_cits (OSCTXT* pctxt, PVD_addGrpD_cits* pvalue);

EXTERN void asn1Print_PVD_addGrpD_cits 
   (const char* name, const PVD_addGrpD_cits* pvalue);

EXTERN int asn1PrtToStr_PVD_addGrpD_cits (const char* name, PVD_addGrpD_cits* pvalue, 
   char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_PVD_addGrpD_cits (OSCTXT *pctxt, 
   const char* name, const PVD_addGrpD_cits* pvalue);

EXTERN PVD_addGrpD_cits* asn1Test_PVD_addGrpD_cits (OSCTXT* pctxt);

EXTERN int asn1Init_PVD_addGrpD_cits (PVD_addGrpD_cits* pvalue);

/**************************************************************/
/*                                                            */
/*  PVD_addGrpD                                               */
/*                                                            */
/**************************************************************/
/*
PVD-addGrpD ::= SEQUENCE {
   cits [0] SEQUENCE (SIZE (1..32)) OF CITSPVD OPTIONAL,
   ...
}
*/
#define TV_PVD_addGrpD	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN PVD_addGrpD {
   struct {
      unsigned citsPresent : 1;
   } m;
   PVD_addGrpD_cits cits;
   OSRTDList extElem1;
} PVD_addGrpD;

EXTERN int asn1E_PVD_addGrpD (OSCTXT* pctxt, PVD_addGrpD *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_PVD_addGrpD (OSCTXT* pctxt, PVD_addGrpD* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_PVD_addGrpD (OSCTXT* pctxt, PVD_addGrpD* pvalue);

EXTERN int OERDec_PVD_addGrpD (OSCTXT* pctxt, PVD_addGrpD* pvalue);

EXTERN int asn1PE_PVD_addGrpD (OSCTXT* pctxt, PVD_addGrpD* pvalue);

EXTERN int asn1PD_PVD_addGrpD (OSCTXT* pctxt, PVD_addGrpD* pvalue);

EXTERN void asn1Print_PVD_addGrpD (const char* name, const PVD_addGrpD* pvalue);

EXTERN int asn1PrtToStr_PVD_addGrpD (const char* name, PVD_addGrpD* pvalue, 
   char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_PVD_addGrpD (OSCTXT *pctxt, 
   const char* name, const PVD_addGrpD* pvalue);

EXTERN PVD_addGrpD* asn1Test_PVD_addGrpD (OSCTXT* pctxt);

EXTERN int asn1Init_PVD_addGrpD (PVD_addGrpD* pvalue);

/**************************************************************/
/*                                                            */
/*  RSA_addGrpD                                               */
/*                                                            */
/**************************************************************/
/*
RSA-addGrpD ::= SEQUENCE {
   cits [0] CITSRSA OPTIONAL,
   ...
}
*/
#define TV_RSA_addGrpD	(TM_UNIV|TM_CONS|16)

typedef struct EXTERN RSA_addGrpD {
   struct {
      unsigned citsPresent : 1;
   } m;
   CITSRSA cits;
   OSRTDList extElem1;
} RSA_addGrpD;

EXTERN int asn1E_RSA_addGrpD (OSCTXT* pctxt, RSA_addGrpD *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_RSA_addGrpD (OSCTXT* pctxt, RSA_addGrpD* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_RSA_addGrpD (OSCTXT* pctxt, RSA_addGrpD* pvalue);

EXTERN int OERDec_RSA_addGrpD (OSCTXT* pctxt, RSA_addGrpD* pvalue);

EXTERN int asn1PE_RSA_addGrpD (OSCTXT* pctxt, RSA_addGrpD* pvalue);

EXTERN int asn1PD_RSA_addGrpD (OSCTXT* pctxt, RSA_addGrpD* pvalue);

EXTERN void asn1Print_RSA_addGrpD (const char* name, const RSA_addGrpD* pvalue);

EXTERN int asn1PrtToStr_RSA_addGrpD (const char* name, RSA_addGrpD* pvalue, 
   char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_RSA_addGrpD (OSCTXT *pctxt, 
   const char* name, const RSA_addGrpD* pvalue);

EXTERN RSA_addGrpD* asn1Test_RSA_addGrpD (OSCTXT* pctxt);

EXTERN int asn1Init_RSA_addGrpD (RSA_addGrpD* pvalue);

#ifdef __cplusplus
}
#endif

#endif
