/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.2.1, Date: 27-Dec-2018.
 */
#ifndef NTCIP_H
#define NTCIP_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtbersrc/asn1ber.h"
#include "rtoersrc/asn1oer.h"
#include "rtpersrc/asn1per.h"

/**
 * Header file for ASN.1 module NTCIP
 */
/**************************************************************/
/*                                                            */
/*  EssPrecipYesNo                                            */
/*                                                            */
/**************************************************************/
/*
EssPrecipYesNo ::= ENUMERATED { precip(1), noPrecip(2), error(3) }
*/
#define TV_EssPrecipYesNo	(TM_UNIV|TM_PRIM|10)

typedef enum {
   precip = 1,
   noPrecip = 2,
   error = 3
} EssPrecipYesNo_Root;

typedef OSUINT32 EssPrecipYesNo;

EXTERN int asn1E_EssPrecipYesNo (OSCTXT* pctxt, EssPrecipYesNo *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_EssPrecipYesNo (OSCTXT* pctxt, EssPrecipYesNo* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_EssPrecipYesNo (OSCTXT* pctxt, EssPrecipYesNo value);

EXTERN int OERDec_EssPrecipYesNo (OSCTXT* pctxt, EssPrecipYesNo* pvalue);

EXTERN int asn1PE_EssPrecipYesNo (OSCTXT* pctxt, EssPrecipYesNo value);

EXTERN int asn1PD_EssPrecipYesNo (OSCTXT* pctxt, EssPrecipYesNo* pvalue);

EXTERN void asn1Print_EssPrecipYesNo (const char* name, const EssPrecipYesNo* pvalue);

EXTERN int asn1PrtToStr_EssPrecipYesNo (const char* name, EssPrecipYesNo* pvalue, 
   char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_EssPrecipYesNo (OSCTXT *pctxt, 
   const char* name, const EssPrecipYesNo* pvalue);

EXTERN const OSUTF8CHAR* EssPrecipYesNo_ToString (OSINT32 value);

EXTERN int EssPrecipYesNo_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, EssPrecipYesNo* pvalue);

EXTERN int EssPrecipYesNo_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, EssPrecipYesNo* pvalue);

EXTERN EssPrecipYesNo* asn1Test_EssPrecipYesNo (OSCTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  EssPrecipRate                                             */
/*                                                            */
/**************************************************************/
/*
EssPrecipRate ::= INTEGER (0..65535)
*/
#define TV_EssPrecipRate	(TM_UNIV|TM_PRIM|2)

typedef OSUINT16 EssPrecipRate;

EXTERN int asn1E_EssPrecipRate (OSCTXT* pctxt, EssPrecipRate *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_EssPrecipRate (OSCTXT* pctxt, EssPrecipRate* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_EssPrecipRate (OSCTXT* pctxt, EssPrecipRate value);

EXTERN int OERDec_EssPrecipRate (OSCTXT* pctxt, EssPrecipRate* pvalue);

EXTERN int asn1PE_EssPrecipRate (OSCTXT* pctxt, EssPrecipRate value);

EXTERN int asn1PD_EssPrecipRate (OSCTXT* pctxt, EssPrecipRate* pvalue);

EXTERN void asn1Print_EssPrecipRate (const char* name, const EssPrecipRate* pvalue);

EXTERN int asn1PrtToStr_EssPrecipRate (const char* name, EssPrecipRate* pvalue, 
   char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_EssPrecipRate (OSCTXT *pctxt, 
   const char* name, const EssPrecipRate* pvalue);

EXTERN EssPrecipRate* asn1Test_EssPrecipRate (OSCTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  EssPrecipSituation                                        */
/*                                                            */
/**************************************************************/
/*
EssPrecipSituation ::= ENUMERATED { other(1), unknown(2), noPrecipitation(3), unidentifiedSlight(4), unidentifiedModerate(5), unidentifiedHeavy(6), snowSlight(7), snowModerate(8), snowHeavy(9), rainSlight(10), rainModerate(11), rainHeavy(12), frozenPrecipitationSlight(13), frozenPrecipitationModerate(14), frozenPrecipitationHeavy(15) }
*/
#define TV_EssPrecipSituation	(TM_UNIV|TM_PRIM|10)

typedef enum {
   other = 1,
   unknown_8 = 2,
   noPrecipitation = 3,
   unidentifiedSlight = 4,
   unidentifiedModerate = 5,
   unidentifiedHeavy = 6,
   snowSlight = 7,
   snowModerate = 8,
   snowHeavy = 9,
   rainSlight = 10,
   rainModerate = 11,
   rainHeavy = 12,
   frozenPrecipitationSlight = 13,
   frozenPrecipitationModerate = 14,
   frozenPrecipitationHeavy = 15
} EssPrecipSituation_Root;

typedef OSUINT32 EssPrecipSituation;

EXTERN int asn1E_EssPrecipSituation (OSCTXT* pctxt, EssPrecipSituation *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_EssPrecipSituation (OSCTXT* pctxt, 
   EssPrecipSituation* pvalue, ASN1TagType tagging, int length);

EXTERN int OEREnc_EssPrecipSituation (OSCTXT* pctxt, EssPrecipSituation value);

EXTERN int OERDec_EssPrecipSituation (OSCTXT* pctxt, EssPrecipSituation* pvalue);

EXTERN int asn1PE_EssPrecipSituation (OSCTXT* pctxt, EssPrecipSituation value);

EXTERN int asn1PD_EssPrecipSituation (OSCTXT* pctxt, EssPrecipSituation* pvalue);

EXTERN void asn1Print_EssPrecipSituation 
   (const char* name, const EssPrecipSituation* pvalue);

EXTERN int asn1PrtToStr_EssPrecipSituation (const char* name, 
   EssPrecipSituation* pvalue, char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_EssPrecipSituation (OSCTXT *pctxt, 
   const char* name, const EssPrecipSituation* pvalue);

EXTERN const OSUTF8CHAR* EssPrecipSituation_ToString (OSINT32 value);

EXTERN int EssPrecipSituation_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, EssPrecipSituation* pvalue);

EXTERN int EssPrecipSituation_ToEnum2 (OSCTXT* pctxt,
   const OSUTF8CHAR* value, OSSIZE valueLen, EssPrecipSituation* pvalue);

EXTERN EssPrecipSituation* asn1Test_EssPrecipSituation (OSCTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  EssSolarRadiation                                         */
/*                                                            */
/**************************************************************/
/*
EssSolarRadiation ::= INTEGER (0..65535)
*/
#define TV_EssSolarRadiation	(TM_UNIV|TM_PRIM|2)

typedef OSUINT16 EssSolarRadiation;

EXTERN int asn1E_EssSolarRadiation (OSCTXT* pctxt, EssSolarRadiation *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_EssSolarRadiation (OSCTXT* pctxt, EssSolarRadiation* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_EssSolarRadiation (OSCTXT* pctxt, EssSolarRadiation value);

EXTERN int OERDec_EssSolarRadiation (OSCTXT* pctxt, EssSolarRadiation* pvalue);

EXTERN int asn1PE_EssSolarRadiation (OSCTXT* pctxt, EssSolarRadiation value);

EXTERN int asn1PD_EssSolarRadiation (OSCTXT* pctxt, EssSolarRadiation* pvalue);

EXTERN void asn1Print_EssSolarRadiation 
   (const char* name, const EssSolarRadiation* pvalue);

EXTERN int asn1PrtToStr_EssSolarRadiation (const char* name, 
   EssSolarRadiation* pvalue, char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_EssSolarRadiation (OSCTXT *pctxt, 
   const char* name, const EssSolarRadiation* pvalue);

EXTERN EssSolarRadiation* asn1Test_EssSolarRadiation (OSCTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  EssMobileFriction                                         */
/*                                                            */
/**************************************************************/
/*
EssMobileFriction ::= INTEGER (0..101)
*/
#define TV_EssMobileFriction	(TM_UNIV|TM_PRIM|2)

typedef OSUINT8 EssMobileFriction;

EXTERN int asn1E_EssMobileFriction (OSCTXT* pctxt, EssMobileFriction *pvalue,
    ASN1TagType tagging);

EXTERN int asn1D_EssMobileFriction (OSCTXT* pctxt, EssMobileFriction* pvalue, 
   ASN1TagType tagging, int length);

EXTERN int OEREnc_EssMobileFriction (OSCTXT* pctxt, EssMobileFriction value);

EXTERN int OERDec_EssMobileFriction (OSCTXT* pctxt, EssMobileFriction* pvalue);

EXTERN int asn1PE_EssMobileFriction (OSCTXT* pctxt, EssMobileFriction value);

EXTERN int asn1PD_EssMobileFriction (OSCTXT* pctxt, EssMobileFriction* pvalue);

EXTERN void asn1Print_EssMobileFriction 
   (const char* name, const EssMobileFriction* pvalue);

EXTERN int asn1PrtToStr_EssMobileFriction (const char* name, 
   EssMobileFriction* pvalue, char* buffer, OSSIZE bufSize);

EXTERN int asn1PrtToStrm_EssMobileFriction (OSCTXT *pctxt, 
   const char* name, const EssMobileFriction* pvalue);

EXTERN EssMobileFriction* asn1Test_EssMobileFriction (OSCTXT* pctxt);

#ifdef __cplusplus
}
#endif

#endif
