/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 7.2.1, Date: 27-Dec-2018.
 */
#ifndef REGION_H
#define REGION_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtbersrc/asn1ber.h"
#include "rtoersrc/asn1oer.h"
#include "rtpersrc/asn1per.h"

#include "AddGrpC.h"
#include "AddGrpB.h"
#include "AddGrpD.h"

/**
 * Header file for ASN.1 module REGION
 */
#ifdef __cplusplus
}
#endif

#endif
